FROM ruby:alpine
WORKDIR /usr/local/app

RUN echo 'http://dl-3.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
    echo 'http://dl-4.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories && \
    echo 'http://dl-4.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache mongodb-tools && \
    rm -rf /var/cache/apk/*
<% if environment == "development" %>
RUN apk add --no-cache make gcc musl-dev curl vim bash git
<% end %>

<% if environment == "development" %>
ADD Gemfile /usr/local/app/Gemfile
ADD Gemfile.lock /usr/local/app/Gemfile.lock
RUN bundle install
<% else %>
ADD . /usr/local/app
RUN bundle install --without development && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem
<% end %>

ENTRYPOINT ["bundle", "exec", "thor"]
