FROM ruby
WORKDIR /usr/local/app

RUN apt-get update && apt-get install -y lsb-release
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
RUN echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" \
 | tee /etc/apt/sources.list.d/mongodb-org-3.4.list
RUN apt-get update
RUN apt-get install -y mongodb-org-tools
<% if environment == "development" %>
RUN apt-get install -y vim
<% end %>

<% if environment == "development" || environment == "test" %>
ADD Gemfile /usr/local/app/Gemfile
ADD Gemfile.lock /usr/local/app/Gemfile.lock
RUN bundle install
<% else %>
ADD . /usr/local/app
RUN bundle install --without development
<% end %>

ENTRYPOINT ["bundle", "exec", "thor"]
