version: "2"
services:
  mongo:
    image: mongo
  fake.s3:
    build: .
    entrypoint: fakes3
    ports:
      - 3000
    command: -r /tmp -p 3000
  app:
    build: .
    entrypoint: tail
    command: -f /dev/null
    volumes:
      - ./:/usr/local/app/
